"""add sync window columns

Revision ID: 0e57bc8ebc7f
Revises: c834bb76be44
Create Date: 2025-08-28 10:26:15.818553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e57bc8ebc7f'
down_revision = 'c834bb76be44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_from_local', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('window_to_local', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('window_from_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('window_to_utc', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_column('window_to_utc')
        batch_op.drop_column('window_from_utc')
        batch_op.drop_column('window_to_local')
        batch_op.drop_column('window_from_local')

    # ### end Alembic commands ###
