"""Add envision_flight_id to SyncFlightLog

Revision ID: 1785b23931b6
Revises: 9640285dde9c
Create Date: 2025-08-29 11:40:35.567331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1785b23931b6'
down_revision = '9640285dde9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_flight_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envision_flight_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sync_flight_log_envision_flight_id'), ['envision_flight_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_flight_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_flight_log_envision_flight_id'))
        batch_op.drop_column('envision_flight_id')

    # ### end Alembic commands ###
