"""initial tables with scheduler config + sync logs

Revision ID: 188f1b4ec06c
Revises: 0e57bc8ebc7f
Create Date: 2025-08-28 11:59:59.822684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188f1b4ec06c'
down_revision = '0e57bc8ebc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_sec', sa.Integer(), nullable=False),
    sa.Column('last_auto_started', sa.DateTime(), nullable=True),
    sa.Column('last_auto_finished', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('initiated_by', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sync_runs_run_type'), ['run_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_run_type'))
        batch_op.drop_column('initiated_by')
        batch_op.drop_column('run_type')

    op.drop_table('app_config')
    # ### end Alembic commands ###
