"""sync run history

Revision ID: 5a8c6b7d9f7e
Revises: a7fd0498523c
Create Date: 2025-08-28 09:53:12.247784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8c6b7d9f7e'
down_revision = 'a7fd0498523c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
