"""Added FO and CC into DB Model

Revision ID: 7b15205458ea
Revises: dfeaa4b2442b
Create Date: 2025-08-30 06:04:26.038486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b15205458ea'
down_revision = 'dfeaa4b2442b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fo_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('fo_empno', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('apg_fo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cc_names', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cc_empnos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('apg_cc_ids', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_fo_empno'), ['fo_empno'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_fo_empno'))
        batch_op.drop_column('apg_cc_ids')
        batch_op.drop_column('cc_empnos')
        batch_op.drop_column('cc_names')
        batch_op.drop_column('apg_fo_id')
        batch_op.drop_column('fo_empno')
        batch_op.drop_column('fo_name')

    # ### end Alembic commands ###
