"""Fix FK to sync_runs and add std/etd

Revision ID: 9640285dde9c
Revises: 188f1b4ec06c
Create Date: 2025-08-29 11:37:57.086753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9640285dde9c'
down_revision = '188f1b4ec06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_flight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('flight_no', sa.String(length=32), nullable=True),
    sa.Column('adep', sa.String(length=4), nullable=True),
    sa.Column('ades', sa.String(length=4), nullable=True),
    sa.Column('eobt_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reg', sa.String(length=32), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('pic_name', sa.String(length=120), nullable=True),
    sa.Column('pic_empno', sa.String(length=32), nullable=True),
    sa.Column('std_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etd_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_flight_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_flight_log_sync_run_id'), ['sync_run_id'], unique=False)

    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_adep'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_ades'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_envision_flight_id'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_eobt'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_flight_no'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_pic_empno'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_reg'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_result'))

    op.drop_table('sync_flight_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_flight_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sync_run_id', sa.INTEGER(), nullable=False),
    sa.Column('envision_flight_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('flight_no', sa.VARCHAR(length=16), nullable=True),
    sa.Column('adep', sa.VARCHAR(length=8), nullable=True),
    sa.Column('ades', sa.VARCHAR(length=8), nullable=True),
    sa.Column('eobt', sa.DATETIME(), nullable=True),
    sa.Column('reg', sa.VARCHAR(length=16), nullable=True),
    sa.Column('aircraft_id', sa.INTEGER(), nullable=True),
    sa.Column('pic_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('pic_empno', sa.VARCHAR(length=32), nullable=True),
    sa.Column('apg_pic_id', sa.INTEGER(), nullable=True),
    sa.Column('result', sa.VARCHAR(length=16), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=256), nullable=True),
    sa.Column('warnings', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_reg'), ['reg'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_pic_empno'), ['pic_empno'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_flight_no'), ['flight_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_eobt'), ['eobt'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_envision_flight_id'), ['envision_flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_ades'), ['ades'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_adep'), ['adep'], unique=False)

    with op.batch_alter_table('sync_flight_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_flight_log_sync_run_id'))

    op.drop_table('sync_flight_log')
    # ### end Alembic commands ###
