"""init

Revision ID: a7fd0498523c
Revises: 
Create Date: 2025-08-28 09:47:59.094666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd0498523c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('source_from', sa.DateTime(), nullable=True),
    sa.Column('source_to', sa.DateTime(), nullable=True),
    sa.Column('flights_count', sa.Integer(), nullable=True),
    sa.Column('pax_count', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('apg_response_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=16), nullable=False),
    sa.Column('flight_date', sa.DateTime(), nullable=False),
    sa.Column('flight_status', sa.String(length=32), nullable=True),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('booking_reference_id', sa.String(length=64), nullable=True),
    sa.Column('name_prefix', sa.String(length=16), nullable=True),
    sa.Column('given_name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('booking_class_code', sa.String(length=8), nullable=True),
    sa.Column('seat', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('iata_status', sa.String(length=32), nullable=True),
    sa.Column('tvl_iata_segment_status', sa.String(length=32), nullable=True),
    sa.Column('baggage_allowance', sa.Float(), nullable=True),
    sa.Column('mobile_phone_number', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('office_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('eticket_number', sa.String(length=64), nullable=True),
    sa.Column('nationality', sa.String(length=48), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_table('flights')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
