"""init sync-only schema

Revision ID: c834bb76be44
Revises: 5a8c6b7d9f7e
Create Date: 2025-08-28 10:21:25.417672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c834bb76be44'
down_revision = '5a8c6b7d9f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_flight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('envision_flight_id', sa.String(length=32), nullable=True),
    sa.Column('flight_no', sa.String(length=16), nullable=True),
    sa.Column('adep', sa.String(length=8), nullable=True),
    sa.Column('ades', sa.String(length=8), nullable=True),
    sa.Column('eobt', sa.DateTime(), nullable=True),
    sa.Column('reg', sa.String(length=16), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('pic_name', sa.String(length=128), nullable=True),
    sa.Column('pic_empno', sa.String(length=32), nullable=True),
    sa.Column('apg_pic_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_adep'), ['adep'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_ades'), ['ades'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_envision_flight_id'), ['envision_flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_eobt'), ['eobt'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_flight_no'), ['flight_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_pic_empno'), ['pic_empno'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_reg'), ['reg'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_flight_logs_result'), ['result'], unique=False)

    op.drop_table('passengers')
    op.drop_table('import_runs')
    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('import_run_id', sa.INTEGER(), nullable=False),
    sa.Column('flight_number', sa.VARCHAR(length=16), nullable=False),
    sa.Column('flight_date', sa.DATETIME(), nullable=False),
    sa.Column('flight_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('origin', sa.VARCHAR(length=8), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('source_from', sa.DATETIME(), nullable=True),
    sa.Column('source_to', sa.DATETIME(), nullable=True),
    sa.Column('flights_count', sa.INTEGER(), nullable=True),
    sa.Column('pax_count', sa.INTEGER(), nullable=True),
    sa.Column('error_summary', sa.TEXT(), nullable=True),
    sa.Column('apg_response_summary', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flight_id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(length=64), nullable=True),
    sa.Column('booking_reference_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name_prefix', sa.VARCHAR(length=16), nullable=True),
    sa.Column('given_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('booking_class_code', sa.VARCHAR(length=8), nullable=True),
    sa.Column('seat', sa.VARCHAR(length=8), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('iata_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('tvl_iata_segment_status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('baggage_allowance', sa.FLOAT(), nullable=True),
    sa.Column('mobile_phone_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('office_phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('eticket_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=48), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_flight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_result'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_reg'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_pic_empno'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_flight_no'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_eobt'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_envision_flight_id'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_ades'))
        batch_op.drop_index(batch_op.f('ix_sync_flight_logs_adep'))

    op.drop_table('sync_flight_logs')
    # ### end Alembic commands ###
